services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    ports:
      - 4000:80

  apache:
    image: httpd:alpine
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./backend:/var/www/html
    ports:
      - 5000:80

  php:
    image: php:fpm-alpine
    volumes:
      - ./backend:/var/www/html
